### ISSUE TITLE
New params syntax & request body handling

### ISSUE THREAD

**Issue by kuzznya** [kuzznya/exposer#5]
For more complex request handling actions, such as getting data from body, new syntax is required

Some ideas:
```yml
params:
  arg0: textArg
  arg1: {{ params.someVal }}
  user: {{ body.username }}
  data: {{ body }}
```

- [X] New syntax
- [x] Split parsing & evaluation
- [x] Request body handling
- [x] Cover with tests
