### ISSUE TITLE
Add path param to endpoint config

### ISSUE THREAD

**Issue by kuzznya** [kuzznya/exposer#9]
Add path parameter to endpoint configuration to enable defining some part of the path directly for the endpoint & simplify some config, e.g.:
```yml
exposer:
  endpoints:
    - path: /test/v1
       ...
    - path: /test/v2
```
